#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os, sys
import subprocess


# Esto debe ejecutarse con sudo.

os.system('docker run -ti --rm -p 9123:80 --name docker-phpmysqldev etsiiull/docker-phpmysqldev /bin/start.sh')
